version: "3"
services:
  frontend:
    depends_on: [backend]
    build: frontend/
    ports:
      - "8080:8080"
    environment: 
      - BACKEND_DNS=backend

  backend:
    depends_on: [db]
    build: backend/
    environment:
      - REDIS_DNS=db

  db:
    image: redis

