name: CI
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: self-hosted
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Run go test
        run: cd frontend && go test
  Build-and-push:
    runs-on: self-hosted
    needs: [Test]
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}

      - name: Build frontend image
        run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-build-frontend.sh

      - name: Push docker frontend
        run: chmod +x ci/push-docker-frontend.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker-frontend.sh

      - name: Build backend image
        run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-build-backend.sh

      - name: Push docker backend
        run: chmod +x ci/push-docker-backend.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker-backend.sh