name: CI
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Run go test
        run: cd frontend && go test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Build frontend
        run:  cd frontend && go build
      - name: Build backend
        run: cd backend && go build
      - name: Upload repo
        uses: actions/upload-artifact@v2
        with:
          name: frontendAndBackend
          path: .
  Push-latest:
     runs-on: ubuntu-latest
     needs: [Test, Build]
     steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: frontendAndBackend
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-org/my-image:latest
